"""add_audit_log

Revision ID: 91973e7e12c7
Revises: f2dcb5c0ec8f
Create Date: 2025-12-29 08:33:21.286835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91973e7e12c7'
down_revision: Union[str, None] = 'f2dcb5c0ec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
