"""Add findings table

Revision ID: f2dcb5c0ec8f
Revises: e3e3435ff7c7
Create Date: 2025-12-29 08:02:30.248303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dcb5c0ec8f'
down_revision: Union[str, None] = 'e3e3435ff7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
